name: Build and deploy documentation book
on: [push]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install mdbook
        shell: bash
        run: |
          mkdir mdbook
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          curl -sSL https://github.com/badboy/mdbook-mermaid/releases/download/v0.10.0/mdbook-mermaid-v0.10.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          curl -sSL https://github.com/tommilligan/mdbook-admonish/releases/download/v1.6.0/mdbook-admonish-v1.6.0-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: Build book
        shell: bash
        run: |
          cd docs/book
          mdbook build
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: book
          path: docs/book/book
      - name: Deploy to GitHub Pages
        if: ${{ github.ref_name == 'main' }}
        shell: bash
        run: |
          cd docs/book
          git worktree add gh-pages gh-pages
          git config user.name "Deploy from CI"
          git config user.email ""
          cd gh-pages
          # Delete the ref to avoid keeping history.
          git update-ref -d refs/heads/gh-pages
          rm -rf *
          mv ../book/* .
          git add .
          git commit -m "Deploy $GITHUB_SHA to gh-pages"
          git push --force
